apiVersion: v1
kind: Service
metadata:
  name: nginx

spec:
  ipFamilies:
  - IPv4
  loadBalancerIP:
  ports:
  - nodePort:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: LoadBalancer
